default_language_version:
    node: lts
exclude: ^web/static/vendored/.+$
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=no]
          - id: trailing-whitespace
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
          - id: python-check-blanket-noqa
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.16.0
      hooks:
          - id: eslint
            additional_dependencies:
                - eslint@8.16.0
                - eslint-config-standard@17.0.0
                - eslint-config-prettier@8.5.0
                - eslint-plugin-import@2.26.0
                - eslint-plugin-n@15.2.0
                - eslint-plugin-promise@6.0.0
                - typescript@4.7.2
                - "@typescript-eslint/parser@5.26.0"
                - "@typescript-eslint/eslint-plugin@5.26.0"
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.6.2
      hooks:
          - id: prettier
            exclude_types: [html]
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/flake8
      rev: &flake8_version 4.0.1
      hooks:
          - &flake8_hook
            id: flake8
            additional_dependencies:
                - flake8-bugbear~=22.4
                - flake8-pytest-style~=1.6
                - pep8-naming~=0.12
    - repo: https://github.com/PyCQA/flake8
      rev: *flake8_version
      hooks:
          - <<: *flake8_hook
            alias: flake8-annotate
            name: flake8 (with annotations)
            stages: [manual]
            args:
                [
                    --format,
                    "::error file=%(path)s,line=%(row)d,col=%(col)d::[flake8] %(code)s: %(text)s",
                ]
