name: Build

on:
    workflow_run:
        workflows: ["Lint & Test"]
        branches:
            - main
        types:
            - completed

jobs:
    build:
        if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push'
        name: Build & Push
        runs-on: ubuntu-latest

        env:
            TAG: ghcr.io/markkoz/pantry-pal:latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  cache-from: type=registry,ref=${{ env.TAG }}
                  cache-to: type=inline
                  tags: ${{ env.TAG }}
